/**
 * generateLevelPack.ts
 *
 * Run with:  npx ts-node generateLevelPack.ts
 * Or:        node --loader ts-node/esm generateLevelPack.ts
 *
 * Outputs: data/sampleLevels.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { generateLevel, DIFFICULTY_LEVELS } from './utils/generator.js';

// ── Configuration ──────────────────────────────────────────────────────────

/** Total number of levels to generate */
const TOTAL_LEVELS = 49;

/**
 * Difficulty ramp:
 * Each entry means "from level X onward, use this difficulty".
 * Entries are evaluated top-to-bottom; the last matching one wins.
 * Adjust thresholds to taste.
 */
const DIFFICULTY_RAMP: Array<{ fromLevel: number; key: keyof typeof DIFFICULTY_LEVELS }> = [
  { fromLevel: 1, key: 'EASY' },
  { fromLevel: 10, key: 'NORMAL' },
  { fromLevel: 50, key: 'HARD' },
  { fromLevel: 50, key: 'EXPERT' },
];

/** Max outer retries per level before giving up and skipping it */
const MAX_RETRIES_PER_LEVEL = 3000;

/** Print a progress dot every N inner retries */
const PROGRESS_DOT_INTERVAL = 200;

// ── Helpers ────────────────────────────────────────────────────────────────

function getDifficulty(levelIndex: number): { key: string; config: typeof DIFFICULTY_LEVELS[string] } {
  let selected = DIFFICULTY_RAMP[0];
  for (const entry of DIFFICULTY_RAMP) {
    if (levelIndex >= entry.fromLevel) selected = entry;
  }
  return { key: selected.key, config: DIFFICULTY_LEVELS[selected.key] };
}

function pad(n: number, width = 2): string {
  return String(n).padStart(width, '0');
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  console.log(`\n🎮  Rush Hour — Level Pack Generator`);
  console.log(`    Generating ${TOTAL_LEVELS} levels...\n`);

  const levels = [];
  const stats: Record<string, { count: number; totalMoves: number; totalAttempts: number }> = {};

  for (let i = 1; i <= TOTAL_LEVELS; i++) {
    const { key: diffName, config: diffConfig } = getDifficulty(i);

    process.stdout.write(
      `  [${pad(i)}/${pad(TOTAL_LEVELS)}] ${diffName.padEnd(6)} ` +
      `(moves ${diffConfig.minMovesRequired}–${diffConfig.maxMovesRequired})  `,
    );

    let level = null;
    let attempts = 0;

    while (!level && attempts < MAX_RETRIES_PER_LEVEL) {
      level = generateLevel(i, diffConfig);
      attempts++;

      if (!level && attempts % PROGRESS_DOT_INTERVAL === 0) {
        process.stdout.write('.');
      }
    }

    if (level) {
      process.stdout.write(`  ✅  ${level.minMoves} moves  (${attempts} attempt${attempts > 1 ? 's' : ''})\n`);
      levels.push(level);

      if (!stats[diffName]) stats[diffName] = { count: 0, totalMoves: 0, totalAttempts: 0 };
      stats[diffName].count++;
      stats[diffName].totalMoves += level.minMoves;
      stats[diffName].totalAttempts += attempts;
    } else {
      process.stdout.write(`  ❌  FAILED after ${attempts} attempts — skipped\n`);
    }
  }

  // ── Write output ─────────────────────────────────────────────────────────
  const outputDir = path.join(process.cwd(), 'data');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const outputPath = path.join(outputDir, 'sampleLevels.ts');
  const fileContent =
    `// Auto-generated by generateLevelPack.ts — do not edit manually.\n` +
    `// Generated: ${new Date().toISOString()}\n` +
    `// Levels: ${levels.length} / ${TOTAL_LEVELS}\n\n` +
    `import { Level } from '@/store/gameStore';\n\n` +
    `export const sampleLevels: Level[] = ${JSON.stringify(levels, null, 2)};\n`;

  fs.writeFileSync(outputPath, fileContent);

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log(`\n─────────────────────────────────────────`);
  console.log(`  Written → ${outputPath}`);
  console.log(`  Total levels: ${levels.length} / ${TOTAL_LEVELS}`);
  console.log();
  console.log('  Difficulty breakdown:');
  for (const [diff, s] of Object.entries(stats)) {
    const avgMoves = (s.totalMoves / s.count).toFixed(1);
    const avgAttempts = (s.totalAttempts / s.count).toFixed(0);
    console.log(`    ${diff.padEnd(6)}  ${s.count} levels  avg ${avgMoves} moves  avg ${avgAttempts} attempts/level`);
  }
  console.log(`─────────────────────────────────────────\n`);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});